import type { PlanCatalogEntry } from '@/types/planCatalog'
import type { TemplateFolder, TemplateExercise, WorkoutTemplate } from '@/types/workout'
import { catalogFolderId } from './catalogFolders'
import { dayTemplate, te } from './planHelpers'

function catalogFolder(slug: string, name: string, purpose: string): TemplateFolder {
  return { id: catalogFolderId(slug), name, purpose }
}

function day(
  id: string,
  name: string,
  folderId: string,
  exercises: TemplateExercise[],
  notes?: string,
): WorkoutTemplate {
  return dayTemplate(id, name, folderId, exercises, notes)
}

function circuitDay(
  id: string,
  name: string,
  folderId: string,
  exercises: TemplateExercise[],
  notes?: string,
): WorkoutTemplate {
  return { id, name, folderId, isCircuit: true, exercises, notes }
}

function fbExercises(
  planId: string,
  variant: 'a' | 'b' | 'c',
): TemplateExercise[] {
  const blocks: Record<'a' | 'b' | 'c', TemplateExercise[]> = {
    a: [
      te(planId, 'squat', 'Goblet Squat', 3, '10-12', '40', false, 'goblet-squat'),
      te(planId, 'press', 'Dumbbell Bench Press', 3, '10-12', '40', false, 'flat-dumbbell-press'),
      te(planId, 'row', 'Dumbbell Row', 3, '10/side', '30', false, 'dumbbell-row'),
      te(planId, 'rdl', 'Dumbbell RDL', 3, '10-12', '30', false, 'dumbbell-romanian-deadlift'),
      te(planId, 'raise', 'Lateral Raise', 3, '12-15', '15', false, 'lateral-raise'),
      te(planId, 'core', 'Plank', 3, '45 sec', '0', false, 'plank'),
    ],
    b: [
      te(planId, 'lunge', 'Walking Lunge', 3, '10/side', '25', false, 'walking-lunge'),
      te(planId, 'incline', 'Incline Dumbbell Press', 3, '10-12', '35', false, 'incline-dumbbell-press'),
      te(planId, 'pulldown', 'Lat Pulldown', 3, '10-12', '80', false, 'lat-pulldown'),
      te(planId, 'hip', 'Hip Thrust', 3, '12', '50', false, 'hip-thrust'),
      te(planId, 'curl', 'Hammer Curl', 2, '10-12', '20', false, 'hammer-curl'),
      te(planId, 'tri', 'Tricep Pushdown', 2, '10-12', '40', false, 'tricep-pushdown'),
    ],
    c: [
      te(planId, 'split', 'Bulgarian Split Squat', 3, '10/side', '25', false, 'bulgarian-split-squat'),
      te(planId, 'ohp', 'Dumbbell Shoulder Press', 3, '10-12', '25', false, 'dumbbell-shoulder-press'),
      te(planId, 'row', 'Chest Supported Row', 3, '10-12', '30', false, 'chest-supported-row'),
      te(planId, 'bridge', 'Glute Bridge', 3, '15', '0', false, 'glute-bridge'),
      te(planId, 'rear', 'Rear Delt Fly', 3, '15', '15', false, 'rear-delt-fly'),
      te(planId, 'core', 'Dead Bug', 3, '10/side', '0', false, 'dead-bug'),
    ],
  }
  return blocks[variant]
}

function gymFbExercises(planId: string, variant: 'a' | 'b' | 'c'): TemplateExercise[] {
  const blocks: Record<'a' | 'b' | 'c', TemplateExercise[]> = {
    a: [
      te(planId, 'squat', 'Barbell Back Squat', 4, '6-8', '135', false, 'squat'),
      te(planId, 'bench', 'Barbell Bench Press', 4, '6-8', '135', false, 'bench-press'),
      te(planId, 'row', 'Barbell Row', 3, '8-10', '115', false, 'barbell-row'),
      te(planId, 'rdl', 'Romanian Deadlift', 3, '8-10', '135', false, 'romanian-deadlift'),
      te(planId, 'ohp', 'Overhead Press', 3, '8-10', '75', false, 'overhead-press'),
      te(planId, 'core', 'Cable Crunch', 3, '12-15', '60', false, 'cable-crunch'),
    ],
    b: [
      te(planId, 'deadlift', 'Trap Bar Deadlift', 4, '5', '185', false, 'trap-bar-deadlift'),
      te(planId, 'incline', 'Incline Dumbbell Press', 3, '8-10', '45', false, 'incline-dumbbell-press'),
      te(planId, 'pulldown', 'Lat Pulldown', 3, '10-12', '90', false, 'lat-pulldown'),
      te(planId, 'lunge', 'Walking Lunge', 3, '10/side', '30', false, 'walking-lunge'),
      te(planId, 'face', 'Face Pull', 3, '15', '50', false, 'face-pull'),
      te(planId, 'curl', 'Barbell Curl', 3, '10-12', '55', false, 'barbell-curl'),
    ],
    c: [
      te(planId, 'leg-press', 'Leg Press', 4, '10-12', '270', false, 'leg-press'),
      te(planId, 'press', 'Machine Chest Press', 3, '10-12', '100', false, 'machine-chest-press'),
      te(planId, 'row', 'Seated Cable Row', 3, '10-12', '90', false, 'seated-cable-row'),
      te(planId, 'curl', 'Leg Curl', 3, '12-15', '80', false, 'hamstring-curl'),
      te(planId, 'lateral', 'Lateral Raise', 3, '15', '20', false, 'lateral-raise'),
      te(planId, 'tri', 'Tricep Pushdown', 3, '12', '50', false, 'tricep-pushdown'),
    ],
  }
  return blocks[variant]
}

function minimalExercises(planId: string, variant: 'a' | 'b' | 'c'): TemplateExercise[] {
  const blocks: Record<'a' | 'b' | 'c', TemplateExercise[]> = {
    a: [
      te(planId, 'squat', 'Bodyweight Squat', 3, '15', '0', true, 'bodyweight-squat'),
      te(planId, 'push', 'Push-Up', 3, '10-15', '0', true, 'push-up'),
      te(planId, 'row', 'Inverted Row', 3, '8-12', '0', true, 'inverted-row'),
      te(planId, 'lunge', 'Walking Lunge', 3, '10/side', '0', true, 'walking-lunge'),
      te(planId, 'plank', 'Plank', 3, '45 sec', '0', true, 'plank'),
    ],
    b: [
      te(planId, 'step', 'Step-Up', 3, '10/side', '0', true, 'step-up'),
      te(planId, 'dip', 'Bench Dip', 3, '10-12', '0', true, 'bench-dip'),
      te(planId, 'pull', 'Pull-Ups', 3, 'AMRAP', '0', true, 'pull-up'),
      te(planId, 'bridge', 'Glute Bridge', 3, '15', '0', true, 'glute-bridge'),
      te(planId, 'mountain', 'Mountain Climber', 3, '30 sec', '0', true, 'mountain-climber'),
    ],
    c: [
      te(planId, 'pistol', 'Pistol Squat Assist', 3, '8/side', '0', true, 'pistol-squat'),
      te(planId, 'pike', 'Pike Push-Up', 3, '10-12', '0', true, 'pike-push-up'),
      te(planId, 'row', 'Towel Row', 3, '12', '0', true, 'inverted-row'),
      te(planId, 'burpee', 'Burpee', 3, '8', '0', true, 'burpee'),
      te(planId, 'hollow', 'Hollow Hold', 3, '30 sec', '0', true, 'hollow-hold'),
    ],
  }
  return blocks[variant]
}

function makeRepeatPlans(
  slug: string,
  folderId: string,
  exerciseFn: (planId: string, v: 'a' | 'b' | 'c') => TemplateExercise[],
  labels = ['A', 'B', 'C'],
): WorkoutTemplate[] {
  return (['a', 'b', 'c'] as const).map((v, i) => {
    const id = `plan-catalog-${slug}-${v}`
    return day(id, `${labels[i] ?? v.toUpperCase()}`, folderId, exerciseFn(id, v))
  })
}

/** Slugs for expansion programs — used by folders, templates, and catalog entries */
export const EXPANSION_SLUGS = [
  'beg-2d-quick',
  'beg-long-3d',
  'beg-db-cut-3d',
  'beg-minimal-2d',
  'int-2d-efficient',
  'int-5d-ul',
  'int-cut-5d',
  'int-strength-3d',
  'int-home-4d',
  'int-db-4d',
  'int-minimal-3d',
  'exp-cut-4d',
  'exp-2d-quick',
  'exp-home-4d',
  'exp-db-4d',
  'exp-minimal-4d',
  'exp-strength-5d',
  'la-cut-5d',
  'la-cut-3d',
  'la-strength-6d',
  'la-home-5d',
  'la-cali-5d',
] as const

export const EXPANSION_CATALOG_FOLDERS: TemplateFolder[] = [
  catalogFolder('beg-2d-quick', 'Beginner 2-Day Quick', 'Two short full-body sessions per week for new lifters.'),
  catalogFolder('beg-long-3d', 'Beginner Long 3-Day', 'Longer beginner full-body sessions with extra accessories.'),
  catalogFolder('beg-db-cut-3d', 'Beginner DB Cut 3-Day', 'Dumbbell circuit training for fat loss at home.'),
  catalogFolder('beg-minimal-2d', 'Beginner Minimal 2-Day', 'Bodyweight-focused training twice per week.'),
  catalogFolder('int-2d-efficient', 'Intermediate 2-Day Efficient', 'Two efficient gym sessions for busy intermediate lifters.'),
  catalogFolder('int-5d-ul', 'Intermediate 5-Day Upper/Lower', 'Five-day upper/lower hypertrophy split.'),
  catalogFolder('int-cut-5d', 'Intermediate Cut 5-Day', 'Five-day recomp split with cardio finishers.'),
  catalogFolder('int-strength-3d', 'Intermediate Strength 3-Day', 'Three-day strength-focused full body.'),
  catalogFolder('int-home-4d', 'Intermediate Home 4-Day', 'Four-day home gym compound training.'),
  catalogFolder('int-db-4d', 'Intermediate DB 4-Day', 'Four-day dumbbell hypertrophy split.'),
  catalogFolder('int-minimal-3d', 'Intermediate Minimal 3-Day', 'Three-day minimal-equipment training.'),
  catalogFolder('exp-cut-4d', 'Experienced Cut 4-Day', 'Four-day cut phase for experienced lifters.'),
  catalogFolder('exp-2d-quick', 'Experienced 2-Day Quick', 'Two quick sessions for experienced lifters short on time.'),
  catalogFolder('exp-home-4d', 'Experienced Home 4-Day', 'Four-day home gym strength and hypertrophy.'),
  catalogFolder('exp-db-4d', 'Experienced DB 4-Day', 'Four-day dumbbell specialization.'),
  catalogFolder('exp-minimal-4d', 'Experienced Minimal 4-Day', 'Four-day calisthenics and bodyweight strength.'),
  catalogFolder('exp-strength-5d', 'Experienced Strength 5-Day', 'Five-day strength emphasis with submaximal loads.'),
  catalogFolder('la-cut-5d', 'Liftaholic Cut 5-Day', 'High-frequency cut training for serious lifters.'),
  catalogFolder('la-cut-3d', 'Liftaholic Quick Cut 3-Day', 'Three-day intense cut circuits.'),
  catalogFolder('la-strength-6d', 'Liftaholic Strength 6-Day', 'Six-day strength-focused high frequency.'),
  catalogFolder('la-home-5d', 'Liftaholic Home 5-Day', 'Five-day home gym high-frequency training.'),
  catalogFolder('la-cali-5d', 'Liftaholic Calisthenics 5-Day', 'Five-day bodyweight volume for minimal setups.'),
]

const F = Object.fromEntries(
  EXPANSION_SLUGS.map((slug) => [slug, catalogFolderId(slug)]),
) as Record<(typeof EXPANSION_SLUGS)[number], string>

export const EXPANSION_CATALOG_PLANS: WorkoutTemplate[] = [
  ...makeRepeatPlans('beg-2d-quick', F['beg-2d-quick'], fbExercises),
  ...makeRepeatPlans('beg-long-3d', F['beg-long-3d'], gymFbExercises),
  ...makeRepeatPlans('beg-db-cut-3d', F['beg-db-cut-3d'], (id, v) =>
    fbExercises(id, v).map((e) => ({ ...e, isCircuit: true })),
  ),
  ...makeRepeatPlans('beg-minimal-2d', F['beg-minimal-2d'], minimalExercises),
  ...makeRepeatPlans('int-2d-efficient', F['int-2d-efficient'], gymFbExercises),
  day('plan-catalog-int-5d-ul-a', 'Upper A', F['int-5d-ul'], [
    te('plan-catalog-int-5d-ul-a', 'bench', 'Barbell Bench Press', 4, '8-10', '155', false, 'bench-press'),
    te('plan-catalog-int-5d-ul-a', 'row', 'Barbell Row', 4, '8-10', '135', false, 'barbell-row'),
    te('plan-catalog-int-5d-ul-a', 'ohp', 'Overhead Press', 3, '8-10', '85', false, 'overhead-press'),
    te('plan-catalog-int-5d-ul-a', 'lat', 'Lat Pulldown', 3, '10-12', '100', false, 'lat-pulldown'),
    te('plan-catalog-int-5d-ul-a', 'curl', 'Barbell Curl', 3, '10-12', '55', false, 'barbell-curl'),
    te('plan-catalog-int-5d-ul-a', 'tri', 'Tricep Pushdown', 3, '10-12', '60', false, 'tricep-pushdown'),
  ]),
  day('plan-catalog-int-5d-ul-b', 'Lower A', F['int-5d-ul'], [
    te('plan-catalog-int-5d-ul-b', 'squat', 'Barbell Back Squat', 4, '6-8', '185', false, 'squat'),
    te('plan-catalog-int-5d-ul-b', 'rdl', 'Romanian Deadlift', 3, '8-10', '155', false, 'romanian-deadlift'),
    te('plan-catalog-int-5d-ul-b', 'leg-press', 'Leg Press', 3, '12-15', '360', false, 'leg-press'),
    te('plan-catalog-int-5d-ul-b', 'curl', 'Leg Curl', 3, '12-15', '90', false, 'hamstring-curl'),
    te('plan-catalog-int-5d-ul-b', 'calf', 'Calf Raise', 4, '15', '135', false, 'calf-raise'),
  ]),
  day('plan-catalog-int-5d-ul-c', 'Upper B', F['int-5d-ul'], [
    te('plan-catalog-int-5d-ul-c', 'incline', 'Incline Dumbbell Press', 4, '8-10', '50', false, 'incline-dumbbell-press'),
    te('plan-catalog-int-5d-ul-c', 'pull', 'Pull-Ups', 4, '6-10', '0', false, 'pull-up'),
    te('plan-catalog-int-5d-ul-c', 'fly', 'Cable Fly', 3, '12-15', '30', false, 'cable-fly'),
    te('plan-catalog-int-5d-ul-c', 'lateral', 'Lateral Raise', 3, '15', '20', false, 'lateral-raise'),
    te('plan-catalog-int-5d-ul-c', 'hammer', 'Hammer Curl', 3, '10-12', '25', false, 'hammer-curl'),
  ]),
  day('plan-catalog-int-5d-ul-d', 'Lower B', F['int-5d-ul'], [
    te('plan-catalog-int-5d-ul-d', 'front', 'Front Squat', 4, '6-8', '135', false, 'front-squat'),
    te('plan-catalog-int-5d-ul-d', 'hip', 'Hip Thrust', 3, '10-12', '185', false, 'hip-thrust'),
    te('plan-catalog-int-5d-ul-d', 'split', 'Bulgarian Split Squat', 3, '10/side', '35', false, 'bulgarian-split-squat'),
    te('plan-catalog-int-5d-ul-d', 'ext', 'Leg Extension', 3, '12-15', '90', false, 'leg-extension'),
    te('plan-catalog-int-5d-ul-d', 'core', 'Cable Crunch', 3, '12-15', '70', false, 'cable-crunch'),
  ]),
  day('plan-catalog-int-5d-ul-e', 'Arms & Delts', F['int-5d-ul'], [
    te('plan-catalog-int-5d-ul-e', 'ohp', 'Dumbbell Shoulder Press', 4, '8-10', '35', false, 'dumbbell-shoulder-press'),
    te('plan-catalog-int-5d-ul-e', 'rear', 'Rear Delt Fly', 3, '15', '20', false, 'rear-delt-fly'),
    te('plan-catalog-int-5d-ul-e', 'curl', 'Incline Dumbbell Curl', 4, '10-12', '25', false, 'incline-dumbbell-curl'),
    te('plan-catalog-int-5d-ul-e', 'skull', 'Skull Crusher', 3, '10-12', '55', false, 'skull-crusher'),
    te('plan-catalog-int-5d-ul-e', 'face', 'Face Pull', 3, '15', '50', false, 'face-pull'),
  ]),
  circuitDay('plan-catalog-int-cut-5d-a', 'Cut Upper A', F['int-cut-5d'], [
    te('plan-catalog-int-cut-5d-a', 'press', 'Machine Chest Press', 3, '12', '100', true, 'machine-chest-press'),
    te('plan-catalog-int-cut-5d-a', 'row', 'Cable Row', 3, '12', '80', true, 'seated-cable-row'),
    te('plan-catalog-int-cut-5d-a', 'lat', 'Lat Pulldown', 3, '12', '80', true, 'lat-pulldown'),
    te('plan-catalog-int-cut-5d-a', 'cardio', 'Incline Walk', 1, '15 min', '0', false, 'treadmill-walk'),
  ]),
  circuitDay('plan-catalog-int-cut-5d-b', 'Cut Lower A', F['int-cut-5d'], [
    te('plan-catalog-int-cut-5d-b', 'squat', 'Goblet Squat', 3, '15', '50', true, 'goblet-squat'),
    te('plan-catalog-int-cut-5d-b', 'rdl', 'Romanian Deadlift', 3, '12', '135', true, 'romanian-deadlift'),
    te('plan-catalog-int-cut-5d-b', 'lunge', 'Walking Lunge', 3, '12/side', '25', true, 'walking-lunge'),
    te('plan-catalog-int-cut-5d-b', 'bike', 'Stationary Bike', 1, '12 min', '0', false, 'stationary-bike'),
  ]),
  circuitDay('plan-catalog-int-cut-5d-c', 'Cut Upper B', F['int-cut-5d'], [
    te('plan-catalog-int-cut-5d-c', 'incline', 'Incline Dumbbell Press', 3, '12', '40', true, 'incline-dumbbell-press'),
    te('plan-catalog-int-cut-5d-c', 'pull', 'Pull-Ups', 3, 'AMRAP', '0', true, 'pull-up'),
    te('plan-catalog-int-cut-5d-c', 'raise', 'Lateral Raise', 3, '15', '20', true, 'lateral-raise'),
    te('plan-catalog-int-cut-5d-c', 'stair', 'Stair Climber', 1, '12 min', '0', false, 'stair-climber'),
  ]),
  circuitDay('plan-catalog-int-cut-5d-d', 'Cut Lower B', F['int-cut-5d'], [
    te('plan-catalog-int-cut-5d-d', 'leg-press', 'Leg Press', 3, '15', '270', true, 'leg-press'),
    te('plan-catalog-int-cut-5d-d', 'curl', 'Leg Curl', 3, '15', '80', true, 'hamstring-curl'),
    te('plan-catalog-int-cut-5d-d', 'hip', 'Hip Thrust', 3, '12', '135', true, 'hip-thrust'),
    te('plan-catalog-int-cut-5d-d', 'rower', 'Rowing Machine', 1, '10 min', '0', false, 'rowing-machine'),
  ]),
  circuitDay('plan-catalog-int-cut-5d-e', 'Cut Full Body', F['int-cut-5d'], [
    te('plan-catalog-int-cut-5d-e', 'kb', 'Kettlebell Swing', 3, '15', '24', true, 'kettlebell-swing'),
    te('plan-catalog-int-cut-5d-e', 'push', 'Push-Up', 3, '15', '0', true, 'push-up'),
    te('plan-catalog-int-cut-5d-e', 'row', 'Dumbbell Row', 3, '12/side', '30', true, 'dumbbell-row'),
    te('plan-catalog-int-cut-5d-e', 'burpee', 'Burpee', 3, '10', '0', true, 'burpee'),
    te('plan-catalog-int-cut-5d-e', 'walk', 'Incline Treadmill Walk', 1, '15 min', '0', false, 'incline-treadmill-walk'),
  ]),
  ...makeRepeatPlans('int-strength-3d', F['int-strength-3d'], gymFbExercises),
  day('plan-catalog-int-home-4d-a', 'Home Upper A', F['int-home-4d'], gymFbExercises('plan-catalog-int-home-4d-a', 'a')),
  day('plan-catalog-int-home-4d-b', 'Home Lower A', F['int-home-4d'], [
    te('plan-catalog-int-home-4d-b', 'squat', 'Goblet Squat', 4, '8-10', '60', false, 'goblet-squat'),
    te('plan-catalog-int-home-4d-b', 'rdl', 'Dumbbell RDL', 4, '8-10', '50', false, 'dumbbell-romanian-deadlift'),
    te('plan-catalog-int-home-4d-b', 'lunge', 'Walking Lunge', 3, '10/side', '35', false, 'walking-lunge'),
    te('plan-catalog-int-home-4d-b', 'hip', 'Hip Thrust', 3, '10-12', '60', false, 'hip-thrust'),
    te('plan-catalog-int-home-4d-b', 'calf', 'Standing Calf Raise', 3, '15', '0', false, 'standing-calf-raise'),
  ]),
  day('plan-catalog-int-home-4d-c', 'Home Upper B', F['int-home-4d'], gymFbExercises('plan-catalog-int-home-4d-c', 'b')),
  day('plan-catalog-int-home-4d-d', 'Home Lower B', F['int-home-4d'], gymFbExercises('plan-catalog-int-home-4d-d', 'c')),
  day('plan-catalog-int-db-4d-a', 'DB Upper A', F['int-db-4d'], fbExercises('plan-catalog-int-db-4d-a', 'a')),
  day('plan-catalog-int-db-4d-b', 'DB Lower A', F['int-db-4d'], fbExercises('plan-catalog-int-db-4d-b', 'b')),
  day('plan-catalog-int-db-4d-c', 'DB Upper B', F['int-db-4d'], fbExercises('plan-catalog-int-db-4d-c', 'c')),
  day('plan-catalog-int-db-4d-d', 'DB Lower B', F['int-db-4d'], fbExercises('plan-catalog-int-db-4d-d', 'a')),
  ...makeRepeatPlans('int-minimal-3d', F['int-minimal-3d'], minimalExercises),
  ...makeRepeatPlans('exp-cut-4d', F['exp-cut-4d'], (id, v) =>
    gymFbExercises(id, v).map((e) => ({ ...e, isCircuit: true })),
  ),
  ...makeRepeatPlans('exp-2d-quick', F['exp-2d-quick'], gymFbExercises),
  day('plan-catalog-exp-home-4d-a', 'Home Strength A', F['exp-home-4d'], gymFbExercises('plan-catalog-exp-home-4d-a', 'a')),
  day('plan-catalog-exp-home-4d-b', 'Home Strength B', F['exp-home-4d'], gymFbExercises('plan-catalog-exp-home-4d-b', 'b')),
  day('plan-catalog-exp-home-4d-c', 'Home Strength C', F['exp-home-4d'], gymFbExercises('plan-catalog-exp-home-4d-c', 'c')),
  day('plan-catalog-exp-home-4d-d', 'Home Strength D', F['exp-home-4d'], fbExercises('plan-catalog-exp-home-4d-d', 'a')),
  day('plan-catalog-exp-db-4d-a', 'DB Power A', F['exp-db-4d'], fbExercises('plan-catalog-exp-db-4d-a', 'a')),
  day('plan-catalog-exp-db-4d-b', 'DB Power B', F['exp-db-4d'], fbExercises('plan-catalog-exp-db-4d-b', 'b')),
  day('plan-catalog-exp-db-4d-c', 'DB Power C', F['exp-db-4d'], fbExercises('plan-catalog-exp-db-4d-c', 'c')),
  day('plan-catalog-exp-db-4d-d', 'DB Power D', F['exp-db-4d'], fbExercises('plan-catalog-exp-db-4d-d', 'c')),
  ...makeRepeatPlans('exp-minimal-4d', F['exp-minimal-4d'], minimalExercises),
  day('plan-catalog-exp-minimal-4d-d', 'Minimal D', F['exp-minimal-4d'], minimalExercises('plan-catalog-exp-minimal-4d-d', 'c')),
  day('plan-catalog-exp-strength-5d-a', 'Heavy Squat', F['exp-strength-5d'], [
    te('plan-catalog-exp-strength-5d-a', 'squat', 'Barbell Back Squat', 5, '3-5', '275', false, 'squat'),
    te('plan-catalog-exp-strength-5d-a', 'bench', 'Paused Bench Press', 4, '4-6', '185', false, 'bench-press'),
    te('plan-catalog-exp-strength-5d-a', 'row', 'Pendlay Row', 4, '6-8', '155', false, 'pendlay-row'),
    te('plan-catalog-exp-strength-5d-a', 'core', 'Ab Wheel Rollout', 3, '8-10', '0', false, 'ab-wheel-rollout'),
  ]),
  day('plan-catalog-exp-strength-5d-b', 'Heavy Deadlift', F['exp-strength-5d'], [
    te('plan-catalog-exp-strength-5d-b', 'deadlift', 'Conventional Deadlift', 5, '2-4', '365', false, 'deadlift'),
    te('plan-catalog-exp-strength-5d-b', 'ohp', 'Overhead Press', 4, '5', '115', false, 'overhead-press'),
    te('plan-catalog-exp-strength-5d-b', 'pull', 'Pull-Ups', 4, '6-8', '0', false, 'pull-up'),
    te('plan-catalog-exp-strength-5d-b', 'face', 'Face Pull', 3, '15', '50', false, 'face-pull'),
  ]),
  day('plan-catalog-exp-strength-5d-c', 'Volume Squat', F['exp-strength-5d'], gymFbExercises('plan-catalog-exp-strength-5d-c', 'a')),
  day('plan-catalog-exp-strength-5d-d', 'Volume Bench', F['exp-strength-5d'], gymFbExercises('plan-catalog-exp-strength-5d-d', 'b')),
  day('plan-catalog-exp-strength-5d-e', 'Volume Deadlift', F['exp-strength-5d'], gymFbExercises('plan-catalog-exp-strength-5d-e', 'c')),
  circuitDay('plan-catalog-la-cut-5d-a', 'LA Cut Push', F['la-cut-5d'], [
    te('plan-catalog-la-cut-5d-a', 'press', 'Incline Dumbbell Press', 4, '12', '45', true, 'incline-dumbbell-press'),
    te('plan-catalog-la-cut-5d-a', 'fly', 'Cable Fly', 3, '15', '30', true, 'cable-fly'),
    te('plan-catalog-la-cut-5d-a', 'tri', 'Tricep Pushdown', 3, '15', '60', true, 'tricep-pushdown'),
    te('plan-catalog-la-cut-5d-a', 'cardio', 'Stair Climber', 1, '15 min', '0', false, 'stair-climber'),
  ]),
  circuitDay('plan-catalog-la-cut-5d-b', 'LA Cut Pull', F['la-cut-5d'], [
    te('plan-catalog-la-cut-5d-b', 'row', 'Chest Supported Row', 4, '12', '100', true, 'chest-supported-row'),
    te('plan-catalog-la-cut-5d-b', 'pulldown', 'Lat Pulldown', 3, '12', '100', true, 'lat-pulldown'),
    te('plan-catalog-la-cut-5d-b', 'curl', 'Hammer Curl', 3, '12', '30', true, 'hammer-curl'),
    te('plan-catalog-la-cut-5d-b', 'bike', 'Stationary Bike', 1, '12 min', '0', false, 'stationary-bike'),
  ]),
  circuitDay('plan-catalog-la-cut-5d-c', 'LA Cut Legs', F['la-cut-5d'], [
    te('plan-catalog-la-cut-5d-c', 'squat', 'Leg Press', 4, '15', '360', true, 'leg-press'),
    te('plan-catalog-la-cut-5d-c', 'rdl', 'Romanian Deadlift', 3, '12', '185', true, 'romanian-deadlift'),
    te('plan-catalog-la-cut-5d-c', 'lunge', 'Walking Lunge', 3, '12/side', '35', true, 'walking-lunge'),
    te('plan-catalog-la-cut-5d-c', 'rower', 'Rowing Machine', 1, '12 min', '0', false, 'rowing-machine'),
  ]),
  circuitDay('plan-catalog-la-cut-5d-d', 'LA Cut Upper', F['la-cut-5d'], gymFbExercises('plan-catalog-la-cut-5d-d', 'a').map((e) => ({ ...e, isCircuit: true }))),
  circuitDay('plan-catalog-la-cut-5d-e', 'LA Cut Full Body', F['la-cut-5d'], [
    te('plan-catalog-la-cut-5d-e', 'kb', 'Kettlebell Swing', 4, '15', '32', true, 'kettlebell-swing'),
    te('plan-catalog-la-cut-5d-e', 'burpee', 'Burpee', 3, '12', '0', true, 'burpee'),
    te('plan-catalog-la-cut-5d-e', 'push', 'Push-Up', 3, '15', '0', true, 'push-up'),
    te('plan-catalog-la-cut-5d-e', 'walk', 'Incline Treadmill Walk', 1, '18 min', '0', false, 'incline-treadmill-walk'),
  ]),
  circuitDay('plan-catalog-la-cut-3d-a', 'LA Quick Cut A', F['la-cut-3d'], [
    te('plan-catalog-la-cut-3d-a', 'circuit', 'Goblet Squat', 3, '15', '50', true, 'goblet-squat'),
    te('plan-catalog-la-cut-3d-a', 'push', 'Push-Up', 3, '15', '0', true, 'push-up'),
    te('plan-catalog-la-cut-3d-a', 'row', 'Cable Row', 3, '12', '80', true, 'seated-cable-row'),
    te('plan-catalog-la-cut-3d-a', 'cardio', 'Assault Bike', 1, '10 min', '0', false, 'assault-bike'),
  ]),
  circuitDay('plan-catalog-la-cut-3d-b', 'LA Quick Cut B', F['la-cut-3d'], [
    te('plan-catalog-la-cut-3d-b', 'kb', 'Kettlebell Swing', 3, '20', '32', true, 'kettlebell-swing'),
    te('plan-catalog-la-cut-3d-b', 'press', 'Dumbbell Shoulder Press', 3, '12', '35', true, 'dumbbell-shoulder-press'),
    te('plan-catalog-la-cut-3d-b', 'lunge', 'Walking Lunge', 3, '12/side', '30', true, 'walking-lunge'),
    te('plan-catalog-la-cut-3d-b', 'stair', 'Stair Climber', 1, '12 min', '0', false, 'stair-climber'),
  ]),
  circuitDay('plan-catalog-la-cut-3d-c', 'LA Quick Cut C', F['la-cut-3d'], [
    te('plan-catalog-la-cut-3d-c', 'leg-press', 'Leg Press', 3, '15', '360', true, 'leg-press'),
    te('plan-catalog-la-cut-3d-c', 'pulldown', 'Lat Pulldown', 3, '12', '100', true, 'lat-pulldown'),
    te('plan-catalog-la-cut-3d-c', 'burpee', 'Burpee', 3, '10', '0', true, 'burpee'),
    te('plan-catalog-la-cut-3d-c', 'walk', 'Incline Treadmill Walk', 1, '15 min', '0', false, 'incline-treadmill-walk'),
  ]),
  day('plan-catalog-la-strength-6d-a', 'LA Strength Squat', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-a', 'a')),
  day('plan-catalog-la-strength-6d-b', 'LA Strength Bench', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-b', 'b')),
  day('plan-catalog-la-strength-6d-c', 'LA Strength Deadlift', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-c', 'c')),
  day('plan-catalog-la-strength-6d-d', 'LA Strength Upper', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-d', 'a')),
  day('plan-catalog-la-strength-6d-e', 'LA Strength Lower', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-e', 'b')),
  day('plan-catalog-la-strength-6d-f', 'LA Strength Full', F['la-strength-6d'], gymFbExercises('plan-catalog-la-strength-6d-f', 'c')),
  day('plan-catalog-la-home-5d-a', 'Home Day A', F['la-home-5d'], fbExercises('plan-catalog-la-home-5d-a', 'a')),
  day('plan-catalog-la-home-5d-b', 'Home Day B', F['la-home-5d'], fbExercises('plan-catalog-la-home-5d-b', 'b')),
  day('plan-catalog-la-home-5d-c', 'Home Day C', F['la-home-5d'], fbExercises('plan-catalog-la-home-5d-c', 'c')),
  day('plan-catalog-la-home-5d-d', 'Home Day D', F['la-home-5d'], fbExercises('plan-catalog-la-home-5d-d', 'a')),
  day('plan-catalog-la-home-5d-e', 'Home Day E', F['la-home-5d'], fbExercises('plan-catalog-la-home-5d-e', 'b')),
  day('plan-catalog-la-cali-5d-a', 'Cali Push', F['la-cali-5d'], minimalExercises('plan-catalog-la-cali-5d-a', 'a')),
  day('plan-catalog-la-cali-5d-b', 'Cali Pull', F['la-cali-5d'], minimalExercises('plan-catalog-la-cali-5d-b', 'b')),
  day('plan-catalog-la-cali-5d-c', 'Cali Legs', F['la-cali-5d'], minimalExercises('plan-catalog-la-cali-5d-c', 'c')),
  day('plan-catalog-la-cali-5d-d', 'Cali Skills', F['la-cali-5d'], minimalExercises('plan-catalog-la-cali-5d-d', 'a')),
  day('plan-catalog-la-cali-5d-e', 'Cali Conditioning', F['la-cali-5d'], minimalExercises('plan-catalog-la-cali-5d-e', 'b')),
]

function repeatIds(slug: string): string[] {
  return ['a', 'b', 'c'].map((v) => `plan-catalog-${slug}-${v}`)
}

export const EXPANSION_CATALOG_SCHEDULE_IDS: Record<string, string[]> = {
  'catalog-beg-2d-quick': repeatIds('beg-2d-quick'),
  'catalog-beg-long-3d': repeatIds('beg-long-3d'),
  'catalog-beg-db-cut-3d': repeatIds('beg-db-cut-3d'),
  'catalog-beg-minimal-2d': repeatIds('beg-minimal-2d'),
  'catalog-int-2d-efficient': repeatIds('int-2d-efficient'),
  'catalog-int-5d-ul': [
    'plan-catalog-int-5d-ul-a',
    'plan-catalog-int-5d-ul-b',
    'plan-catalog-int-5d-ul-c',
    'plan-catalog-int-5d-ul-d',
    'plan-catalog-int-5d-ul-e',
  ],
  'catalog-int-cut-5d': [
    'plan-catalog-int-cut-5d-a',
    'plan-catalog-int-cut-5d-b',
    'plan-catalog-int-cut-5d-c',
    'plan-catalog-int-cut-5d-d',
    'plan-catalog-int-cut-5d-e',
  ],
  'catalog-int-strength-3d': repeatIds('int-strength-3d'),
  'catalog-int-home-4d': [
    'plan-catalog-int-home-4d-a',
    'plan-catalog-int-home-4d-b',
    'plan-catalog-int-home-4d-c',
    'plan-catalog-int-home-4d-d',
  ],
  'catalog-int-db-4d': [
    'plan-catalog-int-db-4d-a',
    'plan-catalog-int-db-4d-b',
    'plan-catalog-int-db-4d-c',
    'plan-catalog-int-db-4d-d',
  ],
  'catalog-int-minimal-3d': repeatIds('int-minimal-3d'),
  'catalog-exp-cut-4d': repeatIds('exp-cut-4d'),
  'catalog-exp-2d-quick': repeatIds('exp-2d-quick'),
  'catalog-exp-home-4d': [
    'plan-catalog-exp-home-4d-a',
    'plan-catalog-exp-home-4d-b',
    'plan-catalog-exp-home-4d-c',
    'plan-catalog-exp-home-4d-d',
  ],
  'catalog-exp-db-4d': [
    'plan-catalog-exp-db-4d-a',
    'plan-catalog-exp-db-4d-b',
    'plan-catalog-exp-db-4d-c',
    'plan-catalog-exp-db-4d-d',
  ],
  'catalog-exp-minimal-4d': [
    'plan-catalog-exp-minimal-4d-a',
    'plan-catalog-exp-minimal-4d-b',
    'plan-catalog-exp-minimal-4d-c',
    'plan-catalog-exp-minimal-4d-d',
  ],
  'catalog-exp-strength-5d': [
    'plan-catalog-exp-strength-5d-a',
    'plan-catalog-exp-strength-5d-b',
    'plan-catalog-exp-strength-5d-c',
    'plan-catalog-exp-strength-5d-d',
    'plan-catalog-exp-strength-5d-e',
  ],
  'catalog-la-cut-5d': [
    'plan-catalog-la-cut-5d-a',
    'plan-catalog-la-cut-5d-b',
    'plan-catalog-la-cut-5d-c',
    'plan-catalog-la-cut-5d-d',
    'plan-catalog-la-cut-5d-e',
  ],
  'catalog-la-cut-3d': repeatIds('la-cut-3d'),
  'catalog-la-strength-6d': [
    'plan-catalog-la-strength-6d-a',
    'plan-catalog-la-strength-6d-b',
    'plan-catalog-la-strength-6d-c',
    'plan-catalog-la-strength-6d-d',
    'plan-catalog-la-strength-6d-e',
    'plan-catalog-la-strength-6d-f',
  ],
  'catalog-la-home-5d': [
    'plan-catalog-la-home-5d-a',
    'plan-catalog-la-home-5d-b',
    'plan-catalog-la-home-5d-c',
    'plan-catalog-la-home-5d-d',
    'plan-catalog-la-home-5d-e',
  ],
  'catalog-la-cali-5d': [
    'plan-catalog-la-cali-5d-a',
    'plan-catalog-la-cali-5d-b',
    'plan-catalog-la-cali-5d-c',
    'plan-catalog-la-cali-5d-d',
    'plan-catalog-la-cali-5d-e',
  ],
}

export const EXPANSION_PLAN_CATALOG_RAW: PlanCatalogEntry[] = [
  {
    id: 'catalog-beg-2d-quick',
    title: 'Beginner 2-Day Quick',
    description: 'Two short full-body sessions per week. Ideal for new lifters with limited time.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'weightLoss', 'liftBig'],
    days: 2,
    duration: 'quick',
    equipment: ['homeGym', 'dumbbellsOnly', 'minimalEquipment', 'commercialGym', 'planetFitness'],
    styles: ['minimalist', 'balanced', 'supersets'],
    volumeScore: 3,
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep progression',
    goalTag: 'Time-efficient',
    scheduleMode: 'folder',
    category: 'beginner',
  },
  {
    id: 'catalog-beg-long-3d',
    title: 'Beginner Long 3-Day',
    description: 'Longer beginner sessions with extra accessories and learning time.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'liftBig'],
    days: 3,
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'compound'],
    volumeScore: 5,
    difficulty: 'Beginner',
    estimatedMinutes: 75,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Double progression',
    goalTag: 'Build foundation',
    scheduleMode: 'folder',
    category: 'beginner',
  },
  {
    id: 'catalog-beg-db-cut-3d',
    title: 'Beginner DB Cut 3-Day',
    description: 'Dumbbell circuit training for fat loss at home or with minimal gear.',
    experienceLevels: ['beginner'],
    goals: ['weightLoss'],
    days: [2, 3],
    duration: ['quick', 'standard'],
    equipment: ['dumbbellsOnly', 'homeGym', 'minimalEquipment'],
    styles: ['supersets', 'minimalist', 'athletic'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 40,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Lose weight',
    scheduleMode: 'folder',
    category: 'beginner',
  },
  {
    id: 'catalog-beg-minimal-2d',
    title: 'Beginner Minimal 2-Day',
    description: 'Bodyweight-focused training twice per week for minimal setups.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'weightLoss', 'size'],
    days: 2,
    duration: ['quick', 'standard'],
    equipment: ['minimalEquipment', 'homeGym'],
    styles: ['minimalist', 'athletic'],
    volumeScore: 3,
    difficulty: 'Beginner',
    estimatedMinutes: 35,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep progression',
    goalTag: 'Bodyweight',
    scheduleMode: 'folder',
    category: 'beginner',
  },
  {
    id: 'catalog-int-2d-efficient',
    title: 'Intermediate 2-Day Efficient',
    description: 'Two efficient gym sessions for busy intermediate lifters.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['strength', 'size', 'liftBig', 'weightLoss'],
    days: 2,
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['minimalist', 'compound', 'balanced'],
    volumeScore: 5,
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Load progression',
    goalTag: 'Time-efficient',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-5d-ul',
    title: 'Intermediate 5-Day Upper/Lower',
    description: 'Five-day upper/lower hypertrophy split with an arm emphasis day.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['size', 'liftBig'],
    days: 5,
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'balanced'],
    volumeScore: 8,
    difficulty: 'Intermediate',
    estimatedMinutes: 70,
    primaryMuscles: ['Upper', 'Lower', 'Arms'],
    progressionStyle: 'Double progression',
    goalTag: 'Hypertrophy',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-cut-5d',
    title: 'Intermediate Cut 5-Day',
    description: 'Five-day recomp split with circuits and cardio finishers.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['weightLoss'],
    days: [4, 5, 6],
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['supersets', 'athletic'],
    volumeScore: 6,
    difficulty: 'Intermediate',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Lose weight',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-strength-3d',
    title: 'Intermediate Strength 3-Day',
    description: 'Three-day strength-focused full body with compound emphasis.',
    experienceLevels: ['intermediate'],
    goals: ['strength', 'liftBig'],
    days: [2, 3, 4],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 7,
    difficulty: 'Intermediate',
    estimatedMinutes: 70,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Linear strength',
    goalTag: 'Build strength',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-home-4d',
    title: 'Intermediate Home 4-Day',
    description: 'Four-day home gym compound training with barbells and dumbbells.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['strength', 'size', 'liftBig'],
    days: [3, 4, 5],
    duration: ['standard', 'long'],
    equipment: ['homeGym'],
    styles: ['compound', 'balanced'],
    volumeScore: 6,
    difficulty: 'Intermediate',
    estimatedMinutes: 60,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Weekly overload',
    goalTag: 'Home training',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-db-4d',
    title: 'Intermediate DB 4-Day',
    description: 'Four-day dumbbell hypertrophy split for home training.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['size', 'strength', 'liftBig'],
    days: [3, 4],
    duration: ['quick', 'standard', 'long'],
    equipment: ['dumbbellsOnly', 'homeGym'],
    styles: ['balanced', 'bodybuilding', 'minimalist'],
    volumeScore: 6,
    difficulty: 'Intermediate',
    estimatedMinutes: 55,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Double progression',
    goalTag: 'Home training',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-int-minimal-3d',
    title: 'Intermediate Minimal 3-Day',
    description: 'Three-day minimal-equipment training with bodyweight and bands.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['strength', 'weightLoss', 'size'],
    days: [2, 3, 4],
    duration: ['quick', 'standard'],
    equipment: ['minimalEquipment', 'homeGym'],
    styles: ['minimalist', 'athletic'],
    volumeScore: 5,
    difficulty: 'Intermediate',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep progression',
    goalTag: 'Bodyweight',
    scheduleMode: 'folder',
    category: 'intermediate',
  },
  {
    id: 'catalog-exp-cut-4d',
    title: 'Experienced Cut 4-Day',
    description: 'Four-day cut phase with supersets for experienced lifters.',
    experienceLevels: ['experienced', 'liftaholic', 'intermediate'],
    goals: ['weightLoss'],
    days: [3, 4, 5],
    duration: ['quick', 'standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym', 'dumbbellsOnly'],
    styles: ['supersets', 'athletic'],
    volumeScore: 7,
    difficulty: 'Advanced',
    estimatedMinutes: 55,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Cut phase',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-exp-2d-quick',
    title: 'Experienced 2-Day Quick',
    description: 'Two quick full-body sessions for experienced lifters short on time.',
    experienceLevels: ['experienced', 'intermediate', 'liftaholic'],
    goals: ['strength', 'size', 'liftBig', 'weightLoss'],
    days: 2,
    duration: 'quick',
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['minimalist', 'compound'],
    volumeScore: 6,
    difficulty: 'Advanced',
    estimatedMinutes: 40,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Load progression',
    goalTag: 'Time-efficient',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-exp-home-4d',
    title: 'Experienced Home 4-Day',
    description: 'Four-day home gym strength and hypertrophy for advanced lifters.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['strength', 'size', 'liftBig'],
    days: [3, 4, 5],
    duration: ['standard', 'long'],
    equipment: ['homeGym'],
    styles: ['compound', 'balanced'],
    volumeScore: 7,
    difficulty: 'Advanced',
    estimatedMinutes: 70,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Weekly overload',
    goalTag: 'Home training',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-exp-db-4d',
    title: 'Experienced DB 4-Day',
    description: 'Four-day dumbbell specialization for experienced home lifters.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['size', 'strength', 'liftBig'],
    days: [3, 4],
    duration: ['standard', 'long'],
    equipment: ['dumbbellsOnly', 'homeGym'],
    styles: ['bodybuilding', 'balanced'],
    volumeScore: 7,
    difficulty: 'Advanced',
    estimatedMinutes: 65,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Double progression',
    goalTag: 'Home training',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-exp-minimal-4d',
    title: 'Experienced Minimal 4-Day',
    description: 'Four-day calisthenics and bodyweight strength progression.',
    experienceLevels: ['experienced', 'intermediate', 'liftaholic'],
    goals: ['strength', 'weightLoss', 'liftBig'],
    days: [3, 4, 5],
    duration: ['quick', 'standard', 'long'],
    equipment: ['minimalEquipment', 'homeGym'],
    styles: ['athletic', 'minimalist'],
    volumeScore: 6,
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Skill + rep progression',
    goalTag: 'Bodyweight',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-exp-strength-5d',
    title: 'Experienced Strength 5-Day',
    description: 'Five-day strength emphasis with heavy and volume days.',
    experienceLevels: ['experienced', 'liftaholic'],
    goals: ['strength', 'liftBig'],
    days: [4, 5, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 8,
    difficulty: 'Advanced',
    estimatedMinutes: 80,
    primaryMuscles: ['Squat', 'Bench', 'Deadlift'],
    progressionStyle: 'Block periodization',
    goalTag: 'Build strength',
    scheduleMode: 'folder',
    category: 'experienced',
  },
  {
    id: 'catalog-la-cut-5d',
    title: 'Liftaholic Cut 5-Day',
    description: 'High-frequency cut training with circuits for serious lifters.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['weightLoss'],
    days: [4, 5, 6, 7],
    duration: ['quick', 'standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym', 'dumbbellsOnly', 'minimalEquipment'],
    styles: ['supersets', 'athletic', 'bodybuilding'],
    volumeScore: 8,
    difficulty: 'Elite',
    estimatedMinutes: 60,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Cut phase',
    scheduleMode: 'folder',
    category: 'liftaholic',
  },
  {
    id: 'catalog-la-cut-3d',
    title: 'Liftaholic Quick Cut 3-Day',
    description: 'Three-day intense cut circuits for liftaholics with limited time.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['weightLoss'],
    days: [2, 3],
    duration: ['quick', 'standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym', 'dumbbellsOnly', 'minimalEquipment'],
    styles: ['supersets', 'athletic', 'minimalist'],
    volumeScore: 7,
    difficulty: 'Elite',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Lose weight',
    scheduleMode: 'folder',
    category: 'liftaholic',
  },
  {
    id: 'catalog-la-strength-6d',
    title: 'Liftaholic Strength 6-Day',
    description: 'Six-day strength-focused high frequency for elite lifters.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['strength', 'liftBig'],
    days: [5, 6, 7],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 9,
    difficulty: 'Elite',
    estimatedMinutes: 75,
    primaryMuscles: ['Squat', 'Bench', 'Deadlift'],
    progressionStyle: 'High-frequency strength',
    goalTag: 'Build strength',
    scheduleMode: 'folder',
    category: 'liftaholic',
  },
  {
    id: 'catalog-la-home-5d',
    title: 'Liftaholic Home 5-Day',
    description: 'Five-day home gym high-frequency training for serious lifters.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'strength', 'liftBig'],
    days: [4, 5, 6],
    duration: ['standard', 'long'],
    equipment: ['homeGym', 'dumbbellsOnly'],
    styles: ['balanced', 'compound', 'bodybuilding'],
    volumeScore: 8,
    difficulty: 'Elite',
    estimatedMinutes: 70,
    primaryMuscles: ['Full body'],
    progressionStyle: 'High-frequency overload',
    goalTag: 'Home training',
    scheduleMode: 'folder',
    category: 'liftaholic',
  },
  {
    id: 'catalog-la-cali-5d',
    title: 'Liftaholic Calisthenics 5-Day',
    description: 'Five-day bodyweight volume for minimal equipment setups.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['strength', 'weightLoss', 'liftBig', 'size'],
    days: [4, 5, 6],
    duration: ['quick', 'standard', 'long'],
    equipment: ['minimalEquipment', 'homeGym'],
    styles: ['athletic', 'minimalist'],
    volumeScore: 8,
    difficulty: 'Elite',
    estimatedMinutes: 55,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Skill + volume progression',
    goalTag: 'Bodyweight',
    scheduleMode: 'folder',
    category: 'liftaholic',
  },
]
