import type { ExperienceLevel, PlanCatalogEntry } from '@/types/planCatalog'
import {
  BEGINNER_FULL_BODY_ID,
  BEGINNER_UPPER_LOWER_FOLDER_ID,
  BEGINNER_WEIGHT_LOSS_ID,
  BUSY_BEGINNER_ID,
  DUMBBELL_STARTER_ID,
  PLANET_FITNESS_STARTER_ID,
} from './beginnerPlans'
import {
  BUSY_PROFESSIONAL_ID,
  INTERMEDIATE_POWERBUILDING_FOLDER_ID,
  INTERMEDIATE_PPL_FOLDER_ID,
  INTERMEDIATE_UL_HYPERTROPHY_FOLDER_ID,
  LEAN_MUSCLE_BUILDER_ID,
  MACHINE_HYPERTROPHY_ID,
} from './intermediatePlans'
import {
  AESTHETIC_VTAPER_FOLDER_ID,
  HIGH_VOLUME_PPL_FOLDER_ID,
  POWERBUILDING_ADVANCED_FOLDER_ID,
  STRENGTH_HYBRID_ID,
  SUMMER_CUT_ID,
  UPPER_LOWER_ARMS_FOLDER_ID,
} from './experiencedPlans'
import {
  ADVANCED_AESTHETICS_FOLDER_ID,
  ARNOLD_PPL_FOLDER_ID,
  DOUBLE_SPLIT_FOLDER_ID,
  HIGH_FREQ_FB_ID,
  LIFTBIG_EXTREME_FOLDER_ID,
  MASS_MONSTER_FOLDER_ID,
} from './liftaholicPlans'
import {
  GUIDED_BEGINNER_FOLDER,
  GUIDED_EXPERIENCED_FOLDER,
  GUIDED_INTERMEDIATE_FOLDER,
  GUIDED_LIFTAHOLIC_FOLDER,
} from './guidedPlanFolders'

const B = GUIDED_BEGINNER_FOLDER.id
const I = GUIDED_INTERMEDIATE_FOLDER.id
const E = GUIDED_EXPERIENCED_FOLDER.id
const L = GUIDED_LIFTAHOLIC_FOLDER.id

/** Curated programs from the Pick a Plan spec */
export const CURATED_PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    id: 'catalog-beginner-full-body-3d',
    title: 'Beginner Full Body (3d)',
    description: 'Simple full-body sessions three times per week. Perfect for learning movement patterns.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'liftBig', 'weightLoss'],
    days: 3,
    duration: 'standard',
    equipment: ['commercialGym', 'homeGym', 'planetFitness'],
    styles: ['balanced', 'minimalist'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 55,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Double progression',
    goalTag: 'Build foundation',
    scheduleMode: 'repeat',
    templateId: BEGINNER_FULL_BODY_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-beginner-upper-lower-4d',
    title: 'Beginner Upper Lower (4d)',
    description: 'Four-day upper/lower split with manageable volume for steady progress.',
    experienceLevels: ['beginner', 'intermediate'],
    goals: ['size', 'strength', 'liftBig'],
    days: 4,
    duration: 'standard',
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'bodybuilding'],
    volumeScore: 5,
    difficulty: 'Beginner',
    estimatedMinutes: 60,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Linear overload',
    goalTag: 'Build muscle',
    scheduleMode: 'folder',
    folderId: BEGINNER_UPPER_LOWER_FOLDER_ID,
    scheduleTemplateIds: [
      'plan-guided-beg-upper-a',
      'plan-guided-beg-lower-a',
      'plan-guided-beg-upper-b',
      'plan-guided-beg-lower-b',
    ],
    category: 'beginner',
  },
  {
    id: 'catalog-busy-beginner',
    title: 'Busy Beginner (3×30)',
    description: 'Quick circuit sessions around 30 minutes. Great when time is tight.',
    experienceLevels: ['beginner'],
    goals: ['weightLoss', 'liftBig', 'size'],
    days: [2, 3],
    duration: 'quick',
    equipment: ['homeGym', 'dumbbellsOnly', 'minimalEquipment', 'commercialGym', 'planetFitness'],
    styles: ['minimalist', 'supersets'],
    volumeScore: 3,
    difficulty: 'Beginner',
    estimatedMinutes: 30,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep progression',
    goalTag: 'Time-efficient',
    scheduleMode: 'repeat',
    templateId: BUSY_BEGINNER_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-beginner-weight-loss',
    title: 'Beginner Weight Loss',
    description: 'Circuit training plus cardio to burn calories while keeping muscle.',
    experienceLevels: ['beginner'],
    goals: ['weightLoss'],
    days: [3, 4],
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['supersets', 'athletic'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Lose weight',
    scheduleMode: 'repeat',
    templateId: BEGINNER_WEIGHT_LOSS_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-planet-fitness-starter',
    title: 'Planet Fitness Starter',
    description: 'Full-body barbell and dumbbell training for Planet Fitness — compounds plus cable accessories.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'weightLoss', 'liftBig'],
    days: [2, 3, 4],
    duration: ['quick', 'standard'],
    equipment: ['planetFitness', 'commercialGym'],
    styles: ['balanced', 'compound'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Double progression',
    goalTag: 'Gym starter',
    scheduleMode: 'repeat',
    templateId: PLANET_FITNESS_STARTER_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-dumbbell-starter',
    title: 'Dumbbell Starter',
    description: 'Full-body dumbbell training for home or minimal equipment setups.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'liftBig'],
    days: [3, 4],
    duration: ['quick', 'standard'],
    equipment: ['dumbbellsOnly', 'homeGym', 'minimalEquipment'],
    styles: ['minimalist', 'balanced'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Double progression',
    goalTag: 'Home training',
    scheduleMode: 'repeat',
    templateId: DUMBBELL_STARTER_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-intermediate-ul-hypertrophy',
    title: 'Upper Lower Hypertrophy',
    description: 'Classic four-day upper/lower split with hypertrophy-focused rep ranges.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['size', 'liftBig'],
    days: 4,
    duration: 'standard',
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['bodybuilding', 'balanced'],
    volumeScore: 7,
    difficulty: 'Intermediate',
    estimatedMinutes: 65,
    primaryMuscles: ['Chest', 'Back', 'Legs'],
    progressionStyle: 'Double progression',
    goalTag: 'Hypertrophy',
    scheduleMode: 'folder',
    folderId: I,
    scheduleTemplateIds: [
      'guided-int-ul-upper-a',
      'guided-int-ul-lower-a',
      'guided-int-ul-upper-b',
      'guided-int-ul-lower-b',
    ],
    category: 'intermediate',
  },
  {
    id: 'catalog-intermediate-ppl',
    title: 'Push Pull Legs',
    description: 'Three-day PPL rotation. Run it once or twice per week depending on recovery.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['size', 'strength', 'liftBig'],
    days: [3, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'bodybuilding', 'compound'],
    volumeScore: 7,
    difficulty: 'Intermediate',
    estimatedMinutes: 70,
    primaryMuscles: ['Push', 'Pull', 'Legs'],
    progressionStyle: 'Weekly overload',
    goalTag: 'Classic split',
    scheduleMode: 'folder',
    folderId: I,
    scheduleTemplateIds: ['guided-int-push', 'guided-int-pull', 'guided-int-legs'],
    category: 'intermediate',
  },
  {
    id: 'catalog-powerbuilding-4d',
    title: 'Powerbuilding 4 Day',
    description: 'Heavy compounds paired with hypertrophy accessories across four days.',
    experienceLevels: ['intermediate', 'experienced'],
    goals: ['strength', 'size', 'liftBig'],
    days: 4,
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 8,
    difficulty: 'Intermediate',
    estimatedMinutes: 75,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Strength + volume waves',
    goalTag: 'Powerbuilding',
    scheduleMode: 'folder',
    folderId: I,
    scheduleTemplateIds: [
      'guided-int-pb-upper',
      'guided-int-pb-lower',
      'guided-int-pb-push',
      'guided-int-pb-pull',
    ],
    category: 'intermediate',
  },
  {
    id: 'catalog-lean-muscle-builder',
    title: 'Lean Muscle Builder',
    description: 'Recomposition-focused training with moderate volume and cardio finishers.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['weightLoss', 'size'],
    days: [3, 4],
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'athletic'],
    volumeScore: 5,
    difficulty: 'Intermediate',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density + load',
    goalTag: 'Lean muscle',
    scheduleMode: 'repeat',
    templateId: LEAN_MUSCLE_BUILDER_ID,
    category: 'intermediate',
  },
  {
    id: 'catalog-busy-professional',
    title: 'Busy Professional',
    description: 'Efficient sessions for lifters with limited time but solid gym experience.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['size', 'strength', 'liftBig', 'weightLoss'],
    days: [3, 4],
    duration: 'quick',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['minimalist', 'machines'],
    volumeScore: 5,
    difficulty: 'Intermediate',
    estimatedMinutes: 40,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Load progression',
    goalTag: 'Time-efficient',
    scheduleMode: 'repeat',
    templateId: BUSY_PROFESSIONAL_ID,
    category: 'intermediate',
  },
  {
    id: 'catalog-machine-hypertrophy',
    title: 'Machine Hypertrophy',
    description: 'Joint-friendly machine volume for consistent hypertrophy stimulus.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['size'],
    days: [3, 4, 5],
    duration: 'standard',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['machines', 'bodybuilding'],
    volumeScore: 6,
    difficulty: 'Intermediate',
    estimatedMinutes: 55,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep range progression',
    goalTag: 'Hypertrophy',
    scheduleMode: 'repeat',
    templateId: MACHINE_HYPERTROPHY_ID,
    category: 'intermediate',
  },
  {
    id: 'catalog-aesthetic-v-taper',
    title: 'Aesthetic V-Taper',
    description: 'Shoulder and back emphasis for the classic V-taper physique.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['size', 'liftBig'],
    days: [3, 4, 5, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['aesthetic', 'bodybuilding'],
    volumeScore: 8,
    difficulty: 'Advanced',
    estimatedMinutes: 75,
    primaryMuscles: ['Shoulders', 'Back', 'Chest'],
    progressionStyle: 'Volume periodization',
    goalTag: 'Aesthetics',
    scheduleMode: 'folder',
    folderId: E,
    scheduleTemplateIds: [
      'guided-exp-vtaper-push',
      'guided-exp-vtaper-pull',
      'guided-exp-vtaper-legs',
    ],
    category: 'experienced',
  },
  {
    id: 'catalog-high-volume-ppl',
    title: 'High Volume PPL',
    description: 'High-volume push/pull/legs for experienced lifters who recover well.',
    experienceLevels: ['experienced', 'liftaholic'],
    goals: ['size', 'liftBig'],
    days: [6, 5],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'balanced'],
    volumeScore: 9,
    difficulty: 'Advanced',
    estimatedMinutes: 90,
    primaryMuscles: ['Push', 'Pull', 'Legs'],
    progressionStyle: 'Wave loading',
    goalTag: 'High volume',
    scheduleMode: 'folder',
    folderId: E,
    scheduleTemplateIds: ['guided-exp-hv-push', 'guided-exp-hv-pull', 'guided-exp-hv-legs'],
    category: 'experienced',
  },
  {
    id: 'catalog-upper-lower-arms',
    title: 'Upper Lower Arms',
    description: 'Upper/lower split with a dedicated arm day for sleeve-stretching volume.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['size', 'liftBig'],
    days: [4, 5],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'aesthetic'],
    volumeScore: 8,
    difficulty: 'Advanced',
    estimatedMinutes: 70,
    primaryMuscles: ['Arms', 'Upper', 'Lower'],
    progressionStyle: 'Specialization blocks',
    goalTag: 'Arms focus',
    scheduleMode: 'folder',
    folderId: E,
    scheduleTemplateIds: [
      'guided-exp-ula-upper',
      'guided-exp-ula-lower',
      'guided-exp-ula-arms',
    ],
    category: 'experienced',
  },
  {
    id: 'catalog-powerbuilding-advanced',
    title: 'Powerbuilding Advanced',
    description: 'Heavy strength days with dedicated accessory work for advanced lifters.',
    experienceLevels: ['experienced', 'liftaholic'],
    goals: ['strength', 'size', 'liftBig'],
    days: [4, 5],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 9,
    difficulty: 'Advanced',
    estimatedMinutes: 85,
    primaryMuscles: ['Squat', 'Bench', 'Deadlift'],
    progressionStyle: 'Block periodization',
    goalTag: 'Strength + size',
    scheduleMode: 'folder',
    folderId: E,
    scheduleTemplateIds: [
      'guided-exp-pb-squat',
      'guided-exp-pb-bench',
      'guided-exp-pb-deadlift',
      'guided-exp-pb-accessory',
    ],
    category: 'experienced',
  },
  {
    id: 'catalog-summer-cut',
    title: 'Summer Cut',
    description: 'Superset-friendly cut phase with cardio finishers to lean out.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['weightLoss'],
    days: [3, 4, 5],
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['supersets', 'athletic'],
    volumeScore: 6,
    difficulty: 'Advanced',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Density progression',
    goalTag: 'Cut phase',
    scheduleMode: 'repeat',
    templateId: SUMMER_CUT_ID,
    category: 'experienced',
  },
  {
    id: 'catalog-strength-hybrid',
    title: 'Strength Hybrid',
    description: 'Strength-first full body with heavy compounds. Repeat 3–4× per week.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['strength', 'liftBig'],
    days: [3, 4],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['compound', 'balanced'],
    volumeScore: 7,
    difficulty: 'Advanced',
    estimatedMinutes: 65,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Linear strength',
    goalTag: 'Build strength',
    scheduleMode: 'repeat',
    templateId: STRENGTH_HYBRID_ID,
    category: 'experienced',
  },
  {
    id: 'catalog-liftbig-extreme',
    title: 'LiftBig Extreme',
    description: 'Maximum volume PPL for lifters who want serious training stimulus.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'liftBig', 'strength'],
    days: [6, 5, 7],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'compound'],
    volumeScore: 10,
    difficulty: 'Elite',
    estimatedMinutes: 95,
    primaryMuscles: ['Push', 'Pull', 'Legs'],
    progressionStyle: 'High-frequency overload',
    goalTag: 'Maximum volume',
    scheduleMode: 'folder',
    folderId: L,
    scheduleTemplateIds: [
      'guided-la-extreme-push',
      'guided-la-extreme-pull',
      'guided-la-extreme-legs',
    ],
    category: 'liftaholic',
  },
  {
    id: 'catalog-arnold-ppl',
    title: 'Arnold x PPL',
    description: 'Classic bodybuilding volume inspired by golden-era splits.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'liftBig'],
    days: [5, 6],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'aesthetic'],
    volumeScore: 10,
    difficulty: 'Elite',
    estimatedMinutes: 90,
    primaryMuscles: ['Chest', 'Back', 'Arms', 'Legs'],
    progressionStyle: 'Volume blocks',
    goalTag: 'Mass building',
    scheduleMode: 'folder',
    folderId: L,
    scheduleTemplateIds: [
      'guided-la-arnold-chest-back',
      'guided-la-arnold-shoulders-arms',
      'guided-la-arnold-legs',
    ],
    category: 'liftaholic',
  },
  {
    id: 'catalog-double-split',
    title: 'Double Split',
    description: 'AM/PM training splits for maximum weekly frequency and volume.',
    experienceLevels: ['liftaholic'],
    goals: ['size', 'liftBig'],
    days: [6, 7],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'supersets'],
    volumeScore: 10,
    difficulty: 'Elite',
    estimatedMinutes: 80,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Twice-daily volume',
    goalTag: 'Extreme frequency',
    scheduleMode: 'folder',
    folderId: L,
    scheduleTemplateIds: [
      'guided-la-ds-am-upper',
      'guided-la-ds-pm-upper',
      'guided-la-ds-am-lower',
      'guided-la-ds-pm-lower',
    ],
    category: 'liftaholic',
  },
  {
    id: 'catalog-mass-monster',
    title: 'Mass Monster',
    description: 'High-volume body part split for maximum hypertrophy stimulus.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'liftBig'],
    days: [5, 6],
    duration: 'long',
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding'],
    volumeScore: 10,
    difficulty: 'Elite',
    estimatedMinutes: 90,
    primaryMuscles: ['Chest', 'Back', 'Legs', 'Shoulders'],
    progressionStyle: 'Specialization overload',
    goalTag: 'Mass building',
    scheduleMode: 'folder',
    folderId: L,
    scheduleTemplateIds: [
      'guided-la-mass-chest',
      'guided-la-mass-back',
      'guided-la-mass-legs',
      'guided-la-mass-shoulders',
    ],
    category: 'liftaholic',
  },
  {
    id: 'catalog-high-freq-full-body',
    title: 'High Frequency Full Body',
    description: 'Full body repeated 5–6× per week with submaximal loads.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['strength', 'liftBig', 'size'],
    days: [5, 6, 7],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound', 'balanced'],
    volumeScore: 9,
    difficulty: 'Elite',
    estimatedMinutes: 70,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Daily undulating',
    goalTag: 'High frequency',
    scheduleMode: 'repeat',
    templateId: HIGH_FREQ_FB_ID,
    category: 'liftaholic',
  },
  {
    id: 'catalog-advanced-aesthetics',
    title: 'Advanced Aesthetics',
    description: 'Refined upper/lower rotation with aesthetic emphasis on proportions.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'liftBig'],
    days: [4, 5, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['aesthetic', 'bodybuilding'],
    volumeScore: 9,
    difficulty: 'Elite',
    estimatedMinutes: 80,
    primaryMuscles: ['Upper', 'Lower'],
    progressionStyle: 'Aesthetic specialization',
    goalTag: 'Aesthetics',
    scheduleMode: 'folder',
    folderId: L,
    scheduleTemplateIds: [
      'guided-la-aesthetics-upper-a',
      'guided-la-aesthetics-lower',
      'guided-la-aesthetics-upper-b',
    ],
    category: 'liftaholic',
  },
]

/** Retrofit existing seeded programs into the catalog */
export const RETROFIT_PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    id: 'catalog-sbd-strength',
    title: 'SBD Strength',
    description: 'Three-week strength block centered on squat, bench, and deadlift.',
    experienceLevels: ['experienced', 'liftaholic', 'intermediate'],
    goals: ['strength', 'liftBig'],
    days: [3, 4, 5],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['compound'],
    volumeScore: 8,
    difficulty: 'Advanced',
    estimatedMinutes: 75,
    primaryMuscles: ['Squat', 'Bench', 'Deadlift'],
    progressionStyle: 'Block periodization',
    goalTag: 'Build strength',
    scheduleMode: 'folder',
    folderId: 'folder-sbd-strength',
    category: 'experienced',
  },
  {
    id: 'catalog-calisthenics-full-body',
    title: 'Calisthenics Full Body',
    description: 'Bodyweight strength and control with minimal equipment.',
    experienceLevels: ['beginner', 'intermediate'],
    goals: ['strength', 'weightLoss', 'liftBig'],
    days: [3, 4],
    duration: ['quick', 'standard'],
    equipment: ['minimalEquipment', 'homeGym'],
    styles: ['athletic', 'minimalist'],
    volumeScore: 5,
    difficulty: 'Beginner',
    estimatedMinutes: 45,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Rep + skill progression',
    goalTag: 'Bodyweight',
    scheduleMode: 'folder',
    folderId: 'folder-calisthenics-full-body',
    category: 'beginner',
  },
  {
    id: 'catalog-joey-summer-ppl',
    title: "Joey's Summer PPL",
    description: 'Push/pull/legs split with core and cut-focused accessories.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['size', 'weightLoss', 'liftBig'],
    days: [3, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['aesthetic', 'bodybuilding'],
    volumeScore: 8,
    difficulty: 'Advanced',
    estimatedMinutes: 75,
    primaryMuscles: ['Push', 'Pull', 'Legs', 'Core'],
    progressionStyle: 'Weekly progression',
    goalTag: 'Summer physique',
    scheduleMode: 'folder',
    folderId: 'folder-joey-summer-cut-split',
    category: 'experienced',
  },
]

/** Broad fallbacks per experience tier — wide metadata for coverage */
export const FALLBACK_PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    id: 'catalog-fallback-beginner',
    title: 'Flexible Beginner',
    description: 'Adaptable full-body training for any beginner goal or schedule.',
    experienceLevels: ['beginner'],
    goals: ['strength', 'size', 'weightLoss', 'liftBig'],
    days: [2, 3, 4, 5],
    duration: ['quick', 'standard'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym', 'dumbbellsOnly', 'minimalEquipment'],
    styles: ['balanced', 'minimalist', 'machines'],
    volumeScore: 4,
    difficulty: 'Beginner',
    estimatedMinutes: 50,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Flexible progression',
    goalTag: 'All-around',
    scheduleMode: 'repeat',
    templateId: BEGINNER_FULL_BODY_ID,
    category: 'beginner',
  },
  {
    id: 'catalog-fallback-intermediate',
    title: 'Flexible Intermediate',
    description: 'Versatile training for intermediate lifters across goals and schedules.',
    experienceLevels: ['intermediate', 'beginner'],
    goals: ['strength', 'size', 'weightLoss', 'liftBig'],
    days: [3, 4, 5, 6],
    duration: ['quick', 'standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'bodybuilding', 'compound'],
    volumeScore: 6,
    difficulty: 'Intermediate',
    estimatedMinutes: 60,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Flexible progression',
    goalTag: 'All-around',
    scheduleMode: 'repeat',
    templateId: LEAN_MUSCLE_BUILDER_ID,
    category: 'intermediate',
  },
  {
    id: 'catalog-fallback-experienced',
    title: 'Flexible Experienced',
    description: 'Solid default for experienced lifters when preferences are mixed.',
    experienceLevels: ['experienced', 'intermediate'],
    goals: ['strength', 'size', 'weightLoss', 'liftBig'],
    days: [3, 4, 5, 6],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness', 'homeGym'],
    styles: ['balanced', 'compound', 'bodybuilding'],
    volumeScore: 7,
    difficulty: 'Advanced',
    estimatedMinutes: 70,
    primaryMuscles: ['Full body'],
    progressionStyle: 'Flexible progression',
    goalTag: 'All-around',
    scheduleMode: 'repeat',
    templateId: STRENGTH_HYBRID_ID,
    category: 'experienced',
  },
  {
    id: 'catalog-fallback-liftaholic',
    title: 'Flexible Liftaholic',
    description: 'High-volume default for serious lifters training most days.',
    experienceLevels: ['liftaholic', 'experienced'],
    goals: ['size', 'liftBig', 'strength'],
    days: [5, 6, 7],
    duration: ['standard', 'long'],
    equipment: ['commercialGym', 'planetFitness'],
    styles: ['bodybuilding', 'compound', 'balanced'],
    volumeScore: 9,
    difficulty: 'Elite',
    estimatedMinutes: 85,
    primaryMuscles: ['Full body'],
    progressionStyle: 'High-volume progression',
    goalTag: 'All-around',
    scheduleMode: 'repeat',
    templateId: HIGH_FREQ_FB_ID,
    category: 'liftaholic',
  },
]

export const ALL_PLAN_CATALOG: PlanCatalogEntry[] = [
  ...CURATED_PLAN_CATALOG,
  ...RETROFIT_PLAN_CATALOG,
  ...FALLBACK_PLAN_CATALOG,
]

export function catalogEntryById(id: string): PlanCatalogEntry | undefined {
  return ALL_PLAN_CATALOG.find((e) => e.id === id)
}

export const EXPERIENCE_CATEGORY_LABELS: Record<ExperienceLevel, string> = {
  beginner: 'Beginner',
  intermediate: 'Intermediate',
  experienced: 'Experienced',
  liftaholic: 'Liftaholic',
}

// Folder ID constants used by catalog (for tests / docs)
export const CATALOG_FOLDER_IDS = {
  beginnerUpperLower: BEGINNER_UPPER_LOWER_FOLDER_ID,
  intermediateUl: INTERMEDIATE_UL_HYPERTROPHY_FOLDER_ID,
  intermediatePpl: INTERMEDIATE_PPL_FOLDER_ID,
  intermediatePowerbuilding: INTERMEDIATE_POWERBUILDING_FOLDER_ID,
  aestheticVtaper: AESTHETIC_VTAPER_FOLDER_ID,
  highVolumePpl: HIGH_VOLUME_PPL_FOLDER_ID,
  upperLowerArms: UPPER_LOWER_ARMS_FOLDER_ID,
  powerbuildingAdvanced: POWERBUILDING_ADVANCED_FOLDER_ID,
  liftbigExtreme: LIFTBIG_EXTREME_FOLDER_ID,
  arnoldPpl: ARNOLD_PPL_FOLDER_ID,
  doubleSplit: DOUBLE_SPLIT_FOLDER_ID,
  massMonster: MASS_MONSTER_FOLDER_ID,
  advancedAesthetics: ADVANCED_AESTHETICS_FOLDER_ID,
} as const
